flashcard_bank = {
	"SYSTEM DESIGN" => [
		["What is the first thing to do in a system design interview?", "Clarify requirements: actors, workflow, scale, constraints, and non-functional requirements."],
		["What are actors in system design?", "The users or external systems interacting with the product."],
		["What is workflow in system design?", "The lifecycle and major steps users or systems follow."],
		["What is meant by source of truth?", "The authoritative system or database responsible for storing canonical data."],
		["What does QPS mean?", "Queries/Requests Per Second."],
		["What are non-functional requirements?", "Reliability, scalability, observability, maintainability, latency, privacy, and availability requirements."],
		["What is the happy path?", "The ideal successful end-to-end user flow through the system."],
		["What are core components in system design?", "APIs, services, databases, queues, caches, and external integrations."],
		["What is idempotency?", "Repeating the same operation multiple times results in the same system state."],
		["What is latency?", "The delay between a user action and system response."],
		["What is vertical scaling?", "Increasing resources on a single machine."],
		["What is horizontal scaling?", "Adding more machines/instances."],
		["What are read replicas?", "Database replicas used to scale read traffic."],
		["What is partitioning?", "Splitting data across systems or tables to distribute load."],
		["What is caching?", "Storing frequently accessed data to reduce repeated computation or DB access."],
		["What is async processing?", "Offloading work to background jobs instead of blocking requests."],
		["What is observability?", "Logs, metrics, traces, dashboards, and alerts used to monitor systems."],
		["What are DLQs?", "Dead Letter Queues for failed background jobs/messages."],
		["What is a tradeoff in system design?", "Choosing one benefit while accepting another limitation."],
		["What is the one-liner to start a whiteboard interview?", "Before I propose architecture, I want to clarify actors, workflow, expected scale, and constraints."],
		["What should you discuss after proposing architecture?", "Failure handling, scaling, observability, security, and tradeoffs."],
		["What are common scaling bottlenecks?", "Database CPU, write bottlenecks, background jobs, external APIs, and network traffic."],
		["What should you ask during requirement clarification?", "Users, scale, latency, consistency, security, compliance, and growth expectations."],
		["What is eventual consistency?", "Data becomes consistent over time rather than immediately."]
	],
	"RUBY ON RAILS - ARCHITECTURE & PATTERNS" => [
		["What is a Service Object?", "A dedicated object encapsulating a business workflow or process."],
		["What is a Decorator Pattern?", "Wraps an object to add presentation behavior without modifying the original object."],
		["What is a Value Object?", "Immutable object representing a domain concept by value rather than identity."],
		["What is a Presenter Pattern?", "Organizes and prepares data for the view layer."],
		["What is a Form Object?", "Handles form validation and persistence outside ActiveRecord models."],
		["What is a Policy Object?", "Encapsulates authorization rules."],
		["What is a Query Object?", "Encapsulates complex query logic outside models/scopes."],
		["What is the Observer Pattern?", "Allows objects to react to state changes/events in other objects."],
		["What is an Interactor Pattern?", "Organizes a single application use case into one object."],
		["What is a Null Object Pattern?", "Replaces nil with a safe default object."],
		["What is an Adapter Pattern?", "Converts one interface into another expected by the application."],
		["What is a Singleton Pattern?", "Ensures only one shared instance exists."],
		["What is a Builder Pattern?", "Constructs complex objects step by step."],
		["What is the difference between design patterns and architectural patterns?", "Design patterns describe object interactions; architectural patterns organize app responsibilities."],
		["What is a Rails anti-pattern?", "A common solution that causes maintainability or design problems over time."],
		["What is a Fat Controller anti-pattern?", "Too much business logic inside controllers."],
		["What is a God Object?", "A model/service doing too many unrelated responsibilities."],
		["What is callback hell?", "Overusing callbacks causing hidden side effects and difficult debugging."],
		["What is an N+1 query?", "Repeated database queries caused by loading associations inefficiently."],
		["What is primitive obsession?", "Overusing raw hashes/strings instead of richer domain objects."],
		["What is DRY?", "Do not Repeat Yourself."],
		["What is SOLID?", "Five OO design principles improving maintainability and flexibility."],
		["What is SRP?", "Single Responsibility Principle: one reason to change."],
		["What is OCP?", "Open/Closed Principle: open for extension, closed for modification."],
		["What is LSP?", "Liskov Substitution Principle: subclasses must behave correctly when substituted."],
		["What is ISP?", "Interface Segregation Principle: avoid forcing unused methods/interfaces."],
		["What is DIP?", "Dependency Inversion Principle: depend on abstractions instead of implementations."],
		["What is KISS?", "Keep It Simple, Stupid."],
		["What is YAGNI?", "You Ain't Gonna Need It."],
		["What is the Law of Demeter?", "Objects should only communicate with close collaborators."],
		["What is composition over inheritance?", "Prefer assembling behavior with objects instead of deep inheritance chains."],
		["What is convention over configuration?", "Rails favors sensible defaults to reduce setup/configuration."],
		["What is metaprogramming?", "Writing code that dynamically defines or modifies behavior at runtime."],
		["What is duck typing?", "Objects are used based on behavior/methods rather than class type."],
		["What is monkey patching?", "Modifying existing classes at runtime."],
		["What is syntactic sugar?", "Syntax that improves readability without changing functionality."],
		["What is polymorphism?", "Different objects responding to the same method differently."],
		["What is encapsulation?", "Bundling data and behavior while hiding implementation details."],
		["What is composition?", "Building behavior by combining objects together."],
		["What is immutability?", "Objects whose state does not change after creation."]
	],
	"RAILS DOCTRINES" => [
		["What does Optimize for programmer happiness mean?", "Rails prioritizes developer productivity and readability."],
		["What does Convention over configuration mean?", "Rails reduces setup by following standard naming and structure conventions."],
		["What does The menu is omakase mean?", "Rails provides curated defaults and integrated tooling."],
		["What does No one paradigm mean?", "Rails supports multiple programming styles."],
		["What does Exalt beautiful code mean?", "Code should be expressive and human-readable."],
		["What does Provide sharp knives mean?", "Rails gives powerful tools even if they can be misused."],
		["What does Value integrated systems mean?", "Rails prefers cohesive built-in solutions over many separate libraries."],
		["What does Progress over stability mean?", "Rails evolves even if upgrades occasionally require changes."],
		["What does Push up a big tent mean?", "Rails supports many use cases and developer skill levels."]
	],
	"RAILS API DESIGN" => [
		["What are the core REST API design components?", "Caching, pagination, rate limiting, authentication, versioning, and error handling."],
		["What does statelessness mean in REST?", "Each request contains all information needed without server-side session memory."],
		["What HTTP method retrieves data?", "GET."],
		["What HTTP method creates data?", "POST."],
		["What HTTP method updates data?", "PUT/PATCH."],
		["What HTTP method deletes data?", "DELETE."],
		["What is pagination?", "Splitting large datasets into smaller pages."],
		["What is rate limiting?", "Restricting request frequency to prevent abuse."],
		["What is authentication?", "Verifying identity."],
		["What is authorization?", "Determining permissions/access rights."],
		["What is JWT?", "JSON Web Token used for stateless authentication."],
		["What is OAuth2?", "Authorization framework for delegated access."],
		["What is CORS?", "Rules controlling which frontends may access an API."],
		["What is serialization?", "Shaping/modeling API response data."],
		["What causes N+1 queries?", "Loading associations inefficiently without eager loading."],
		["What Rails method fixes N+1 queries?", "includes."],
		["What is API versioning?", "Maintaining separate API versions like /api/v1."],
		["What is observability in APIs?", "Logging, metrics, tracing, and monitoring."],
		["What is a 401 status code?", "Unauthorized."],
		["What is a 403 status code?", "Forbidden."],
		["What is a 422 status code?", "Unprocessable Entity / validation failure."],
		["What is a 500 status code?", "Internal Server Error."]
	],
	"RAILS ERROR HANDLING" => [
		["What is begin/rescue used for?", "Ruby-level exception handling."],
		["Where is begin/rescue commonly used?", "Service objects, jobs, API calls, and data processing."],
		["What does flash[:alert] do?", "Displays temporary messages to users in HTML responses."],
		["Are flash messages used in APIs?", "No, APIs use JSON error responses instead."],
		["What is @model.errors used for?", "Model validation error messages."],
		["What is rescue_from used for?", "Global Rails controller-level error handling."],
		["What layer handles business logic errors?", "Ruby/service object layer."],
		["What layer handles validation errors?", "Models."],
		["What layer handles request/response errors?", "Controllers."],
		["What layer handles async failures?", "Background jobs."]
	],
	"REACT - CORE CONCEPTS" => [
		["What is a React component?", "Reusable UI building block returning JSX."],
		["What is JSX?", "JavaScript syntax extension for describing UI structure."],
		["What are props?", "Read-only inputs passed from parent to child components."],
		["What is state?", "Component-managed mutable data."],
		["What are hooks?", "Functions enabling state and lifecycle behavior in function components."],
		["What does useState do?", "Adds state to a functional component."],
		["What does useEffect do?", "Handles side effects like API calls and subscriptions."],
		["What is conditional rendering?", "Rendering different UI based on conditions."],
		["What are keys in React lists?", "Unique identifiers for efficiently rendering collections."],
		["What is component composition?", "Building UIs by combining components."],
		["What is Context?", "Mechanism for sharing data without prop drilling."],
		["What is a controlled component?", "Form element controlled by React state."],
		["What is an uncontrolled component?", "Form element managed directly by the DOM via refs."],
		["What are fragments?", "Group elements without adding extra DOM nodes."],
		["What are custom hooks?", "Reusable hook-based logic shared across components."],
		["What is the Virtual DOM?", "Lightweight in-memory representation of the real DOM."],
		["What is one-way data flow?", "Data flows from parent to child only."],
		["What is prop destructuring?", "Extracting props into variables for cleaner code."]
	],
	"REACT HOOKS" => [
		["What does useReducer do?", "Manages complex state using reducer functions."],
		["What does useLayoutEffect do?", "Runs synchronously after DOM mutations but before paint."],
		["What does useRef do?", "Stores mutable values or references DOM elements."],
		["What does useMemo do?", "Memoizes expensive calculations."],
		["What does useCallback do?", "Memoizes callback functions to avoid unnecessary recreation."],
		["What does useContext do?", "Accesses React Context values."],
		["What does useTransition do?", "Marks non-urgent UI updates to keep interfaces responsive."],
		["What does useId do?", "Generates unique component IDs."],
		["What is a custom hook?", "Reusable function encapsulating hook-based behavior."]
	],
	"REACT TESTING" => [
		["What is the core React testing philosophy?", "Test behavior, not implementation details."],
		["What should React tests focus on?", "User-visible behavior, interactions, and important state transitions."],
		["What should you avoid over-testing?", "Styling, internal implementation details, and duplicate tests."],
		["What important UI states should be tested?", "Loading, error, empty, and success states."],
		["What are core user flows to test?", "Create, update, delete, load, and filter actions."],
		["What is a useful React testing mental model?", "If users would notice it breaking, test it."]
	],
	"AWS SOLUTIONS ARCHITECT - ASSOCIATE (SAA-C03)" => [
		["What is EC2?", "Elastic Compute Cloud — virtual servers in AWS."],
		["What is S3?", "Scalable object storage service."],
		["What is RDS?", "Managed relational database service."],
		["What is DynamoDB?", "Managed NoSQL key-value database."],
		["What is Lambda?", "Serverless compute service that runs code on demand."],
		["What is IAM?", "Identity and Access Management for AWS permissions and authentication."],
		["What is a VPC?", "Virtual Private Cloud — isolated AWS network environment."],
		["What is Route 53?", "AWS DNS and domain routing service."],
		["What is CloudFront?", "AWS CDN for caching and low-latency content delivery."],
		["What is an Availability Zone?", "Isolated AWS datacenter within a region."],
		["What is an AWS Region?", "Geographic area containing multiple AZs."],
		["What is Auto Scaling?", "Automatically adjusts compute resources based on load."],
		["What is Elastic Load Balancing?", "Distributes incoming traffic across multiple targets."],
		["What is EBS?", "Elastic Block Store — persistent block storage for EC2."],
		["What is EFS?", "Elastic File System — scalable shared file storage."],
		["What is SNS?", "Simple Notification Service for pub/sub messaging."],
		["What is SQS?", "Simple Queue Service for message queues."],
		["What is CloudWatch?", "Monitoring, metrics, logging, and alerts service."],
		["What is CloudTrail?", "AWS API activity auditing and logging service."],
		["What is Secrets Manager?", "Secure secrets/password storage service."],
		["What is Parameter Store?", "Systems Manager feature for config and secrets storage."],
		["What is ECS?", "Elastic Container Service for container orchestration."],
		["What is EKS?", "Managed Kubernetes service."],
		["What is Fargate?", "Serverless container runtime for ECS/EKS."],
		["What is API Gateway?", "Managed API creation and routing service."],
		["What is NAT Gateway?", "Allows private subnet outbound internet access."],
		["What is an Internet Gateway?", "Enables internet connectivity for a VPC."],
		["What is least privilege?", "Granting only minimum permissions required."],
		["What is horizontal scaling?", "Adding more instances to distribute load."],
		["What is vertical scaling?", "Increasing resources on a single machine."],
		["What is Multi-AZ in RDS?", "High availability deployment across Availability Zones."],
		["What is an S3 lifecycle policy?", "Automated movement/deletion of S3 objects over time."],
		["What is eventual consistency?", "Data consistency achieved over time after updates."],
		["What is high availability?", "Designing systems to minimize downtime."],
		["What is fault tolerance?", "System continues operating despite failures."],
		["What is disaster recovery?", "Restoring systems after catastrophic failure."],
		["What is caching in AWS commonly done with?", "CloudFront, ElastiCache, or API caching."],
		["What is ElastiCache?", "Managed Redis/Memcached service."],
		["What is Infrastructure as Code?", "Managing infrastructure through code/templates."],
		["What is CloudFormation?", "AWS Infrastructure-as-Code service."],
		["What is Terraform?", "Third-party Infrastructure-as-Code tool."],
		["What is shared responsibility model?", "AWS secures cloud infrastructure; customers secure workloads/data."],
		["What is a security group?", "Virtual firewall controlling instance traffic."],
		["What is a subnet?", "Segmented IP range inside a VPC."],
		["What is a private subnet?", "Subnet without direct internet access."],
		["What is a public subnet?", "Subnet with internet connectivity."],
		["What is AWS Well-Architected Framework?", "AWS best-practices framework for reliable/scalable systems."],
		["What are the pillars of Well-Architected?", "Operational Excellence, Security, Reliability, Performance Efficiency, Cost Optimization, Sustainability."],
		["What is cost optimization?", "Designing systems to reduce unnecessary AWS spending."],
		["What is serverless?", "Running workloads without managing servers directly."],
		["What is IAM Role vs IAM User?", "Role is assumable temporary permissions; user is permanent identity."],
		["What is presigned URL in S3?", "Temporary secure URL granting access to an object."],
		["What is RTO?", "Recovery Time Objective — acceptable downtime duration."],
		["What is RPO?", "Recovery Point Objective — acceptable data loss window."],
		["What is a dead-letter queue?", "Queue storing failed/unprocessed messages."],
		["What is decoupling?", "Separating system components to reduce dependencies."],
		["What is an event-driven architecture?", "Systems react to events/messages asynchronously."],
		["What is a blue/green deployment?", "Switching traffic between old and new environments safely."],
		["What is immutable infrastructure?", "Replacing infrastructure instead of modifying in place."]
	],
	"GITHUB ACTIONS / GH-200" => [
		["What is GitHub Actions?", "GitHub's CI/CD and automation platform."],
		["What is a workflow in GitHub Actions?", "Automated process defined in YAML."],
		["Where are workflows stored?", ".github/workflows directory."],
		["What triggers a workflow?", "Events like push, pull_request, workflow_dispatch, or schedule."],
		["What is a job in GitHub Actions?", "A group of steps executed on the same runner."],
		["What is a step in GitHub Actions?", "Individual command or action inside a job."],
		["What is a runner?", "Machine/environment executing workflow jobs."],
		["What is GitHub-hosted runner?", "Managed runner provided by GitHub."],
		["What is a self-hosted runner?", "Runner managed by your own infrastructure."],
		["What does uses: do in workflows?", "References reusable GitHub Actions."],
		["What does run: do in workflows?", "Executes shell commands."],
		["What is checkout action commonly used for?", "Pulling repository code into the runner."],
		["What is actions/checkout?", "Official GitHub Action for checking out repo code."],
		["What is actions/setup-node?", "Action for configuring Node.js environments."],
		["What is a workflow_dispatch trigger?", "Manual workflow execution trigger."],
		["What is a matrix strategy?", "Running jobs across multiple environments/configurations."],
		["What are secrets in GitHub Actions?", "Secure encrypted environment variables."],
		["Where are GitHub secrets stored?", "Repository, environment, or organization settings."],
		["What is CI?", "Continuous Integration."],
		["What is CD?", "Continuous Delivery/Deployment."],
		["What is artifact upload?", "Storing build/test output from workflows."],
		["What is caching in GitHub Actions?", "Reusing dependencies/files between workflow runs."],
		["What is dependency caching commonly used for?", "npm, bundler, yarn, pip, Maven dependencies."],
		["What is concurrency in GitHub Actions?", "Controlling simultaneous workflow execution."],
		["What is environment protection?", "Approval rules before deployment."],
		["What is reusable workflow?", "Workflow callable from another workflow."],
		["What is composite action?", "Reusable group of workflow steps."],
		["What is the difference between jobs and steps?", "Jobs run independently; steps run sequentially within jobs."],
		["What is fail-fast behavior?", "Cancels remaining matrix jobs when one fails."],
		["What is a pull_request trigger?", "Runs workflow when PR events occur."],
		["What is a push trigger?", "Runs workflow after commits are pushed."],
		["What is schedule trigger?", "Cron-based automated workflow execution."],
		["What is workflow_run?", "Triggering workflows after another workflow completes."],
		["What is a deployment environment?", "Named deployment target with rules/secrets."],
		["What is required approval in Actions?", "Manual approval gate before deployment proceeds."],
		["What is GitHub Packages?", "GitHub-hosted package/container registry."],
		["What is GITHUB_TOKEN?", "Auto-generated token for workflow authentication."],
		["What is OIDC in GitHub Actions?", "OpenID Connect authentication for cloud providers without long-lived secrets."],
		["What is least privilege in CI/CD?", "Granting workflows only required permissions."],
		["What is branch protection?", "Rules restricting direct pushes/merges to branches."],
		["What is status check enforcement?", "Requiring workflows/tests before merging."],
		["What is a YAML workflow file?", "Declarative config defining automation pipelines."],
		["What is deployment automation?", "Automatically releasing applications after validation/testing."],
		["What is a typical CI pipeline flow?", "Checkout → install deps → run tests → build → deploy."],
		["What is a rollback strategy?", "Mechanism to revert failed deployments safely."],
		["What is artifact retention?", "How long workflow artifacts are stored."],
		["What is monorepo workflow optimization?", "Running jobs only for changed directories/services."],
		["What is path filtering?", "Triggering workflows only for specific file changes."],
		["What is GitHub Environments used for?", "Managing deployment-specific rules and secrets."],
		["What is semantic versioning?", "Version format MAJOR.MINOR.PATCH."],
		["What is Infrastructure as Code in CI/CD?", "Automating infrastructure provisioning through code."],
		["What is a deployment gate?", "Condition/check before deployment executes."],
		["What is observability in CI/CD?", "Logs, metrics, traces, and monitoring for pipelines."],
		["What is ephemeral infrastructure?", "Temporary short-lived infrastructure spun up dynamically."],
		["What is continuous delivery vs deployment?", "Delivery requires manual approval; deployment is fully automatic."]
	],
	"RUBY METHODS" => [
		["What does map do in Ruby?", "Transforms each element in a collection and returns a new array."],
		["What does each do in Ruby?", "Iterates over each element in a collection."],
		["What does select do in Ruby?", "Returns elements matching a condition."],
		["What does reject do in Ruby?", "Returns elements NOT matching a condition."],
		["What does find do in Ruby?", "Returns the first matching element."],
		["What does detect do in Ruby?", "Alias for find."],
		["What does reduce do in Ruby?", "Combines elements into a single accumulated value."],
		["What does inject do in Ruby?", "Alias for reduce."],
		["What does any? do in Ruby?", "Returns true if any element matches a condition."],
		["What does all? do in Ruby?", "Returns true if all elements match a condition."],
		["What does none? do in Ruby?", "Returns true if no elements match a condition."],
		["What does include? do in Ruby?", "Checks whether a collection contains a value."],
		["What does empty? do in Ruby?", "Checks whether a collection has no elements."],
		["What does present? do in Rails?", "Checks if an object exists and is not blank."],
		["What does nil? do in Ruby?", "Checks whether an object is nil."],
		["What does blank? do in Rails?", "Checks if object is nil, empty, or whitespace."],
		["What does compact do in Ruby?", "Removes nil values from arrays/hashes."],
		["What does flatten do in Ruby?", "Converts nested arrays into a single-level array."],
		["What does uniq do in Ruby?", "Removes duplicate elements."],
		["What does sort do in Ruby?", "Sorts elements in ascending order."],
		["What does reverse do in Ruby?", "Reverses collection order."],
		["What does merge do in Ruby?", "Combines hashes together."],
		["What does symbolize_keys do in Rails?", "Converts hash keys to symbols."],
		["What does deep_symbolize_keys do in Rails?", "Recursively converts nested hash keys to symbols."],
		["What does slice do in Ruby/Rails?", "Returns selected keys from a hash."],
		["What does dig do in Ruby?", "Safely accesses nested hash/array values."],
		["What does fetch do in Ruby?", "Retrieves a hash value with optional default/error handling."],
		["What does join do in Ruby?", "Combines array elements into a string."],
		["What does split do in Ruby?", "Splits a string into an array."],
		["What does strip do in Ruby?", "Removes leading/trailing whitespace."],
		["What does gsub do in Ruby?", "Replaces all matching substrings."],
		["What does sub do in Ruby?", "Replaces first matching substring."],
		["What does downcase do in Ruby?", "Converts string to lowercase."],
		["What does upcase do in Ruby?", "Converts string to uppercase."],
		["What does capitalize do in Ruby?", "Capitalizes first character."],
		["What does symbolize_names do in JSON parsing?", "Converts JSON keys into symbols."],
		["What does to_i do in Ruby?", "Converts value to integer."],
		["What does to_f do in Ruby?", "Converts value to float."],
		["What does to_s do in Ruby?", "Converts value to string."],
		["What does to_h do in Ruby?", "Converts object to hash."],
		["What does to_a do in Ruby?", "Converts object to array."],
		["What does freeze do in Ruby?", "Makes an object immutable."],
		["What does private do in Ruby?", "Restricts method visibility to internal use."],
		["What does attr_accessor do in Ruby?", "Creates getter and setter methods."],
		["What does attr_reader do in Ruby?", "Creates getter methods only."],
		["What does attr_writer do in Ruby?", "Creates setter methods only."],
		["What does lambda do in Ruby?", "Creates anonymous callable function object."],
		["What does proc do in Ruby?", "Creates callable block-like object."],
		["What does yield do in Ruby?", "Executes a provided block inside a method."],
		["What does respond_to? do in Ruby?", "Checks whether object supports a method."],
		["What does send do in Ruby?", "Dynamically invokes a method."],
		["What does public_send do in Ruby?", "Dynamically invokes public methods only."],
		["What does is_a? do in Ruby?", "Checks object class/type inheritance."],
		["What does class do in Ruby?", "Returns object's class."],
		["What does between? do in Ruby?", "Checks whether value falls within range."],
		["What does times do in Ruby?", "Repeats block specified number of times."],
		["What does upto do in Ruby?", "Iterates upward through range of values."],
		["What does ||= do in Ruby?", "Assigns value only if variable is nil/false."],
		["What does safe navigation (&.) do in Ruby?", "Prevents nil errors when chaining methods."],
		["What does memoization mean in Ruby?", "Caching computed value to avoid repeated work."],
		["What does begin/rescue do in Ruby?", "Handles exceptions/errors."],
		["What does ensure do in Ruby?", "Executes code regardless of exceptions."],
		["What does raise do in Ruby?", "Raises an exception/error."]
	],
	"RAILS METHODS" => [
		["What does before_action do in Rails?", "Runs controller logic before actions execute."],
		["What does has_many do in Rails?", "Defines one-to-many ActiveRecord association."],
		["What does belongs_to do in Rails?", "Defines parent association relationship."],
		["What does validates do in Rails?", "Adds model validations."],
		["What does scope do in Rails?", "Defines reusable query logic."],
		["What does includes do in Rails?", "Eager loads associations to avoid N+1 queries."],
		["What does where do in Rails?", "Filters database records."],
		["What does find do in Rails?", "Finds record by primary key."],
		["What does find_by do in Rails?", "Finds first matching record by attributes."],
		["What does order do in Rails?", "Sorts query results."],
		["What does limit do in Rails?", "Restricts number of returned records."],
		["What does pluck do in Rails?", "Retrieves specific DB columns efficiently."],
		["What does select do in ActiveRecord?", "Limits selected DB columns or filters collections."],
		["What does joins do in Rails?", "Performs SQL joins between tables."],
		["What does left_joins do in Rails?", "Performs LEFT OUTER JOIN queries."],
		["What does group do in Rails?", "Groups query results."],
		["What does count do in Rails?", "Counts records."],
		["What does sum do in Rails?", "Sums numeric DB values."],
		["What does average do in Rails?", "Calculates average DB value."],
		["What does update do in Rails?", "Updates model attributes."],
		["What does update_all do in Rails?", "Bulk updates records without validations/callbacks."],
		["What does destroy do in Rails?", "Deletes record with callbacks."],
		["What does delete do in Rails?", "Deletes record without callbacks."],
		["What does save do in Rails?", "Persists model to database."],
		["What does save! do in Rails?", "Saves model and raises exception on failure."],
		["What does create do in Rails?", "Instantiates and saves model."],
		["What does create! do in Rails?", "Creates record and raises exception on failure."],
		["What does reload do in Rails?", "Reloads model data from database."],
		["What does transaction do in Rails?", "Wraps DB operations atomically."],
		["What does render do in Rails?", "Returns view/template/JSON response."],
		["What does redirect_to do in Rails?", "Redirects browser to another route."],
		["What does head do in Rails?", "Returns response with headers/status only."],
		["What does permit do in Rails?", "Whitelists request parameters."],
		["What does require do in strong params?", "Requires parameter presence."],
		["What does present? do in Rails?", "Checks object exists and is not blank."],
		["What does blank? do in Rails?", "Checks nil/empty/whitespace values."],
		["What does touch do in Rails?", "Updates timestamps without modifying attributes."],
		["What does dependent: :destroy do?", "Deletes associated records automatically."],
		["What does inverse_of do in Rails?", "Improves association consistency and memory usage."],
		["What does enum do in Rails?", "Maps symbolic states to integers."],
		["What does serialize do in Rails?", "Stores structured objects in DB column."],
		["What does accepts_nested_attributes_for do?", "Allows nested form/model updates."],
		["What does delegate do in Rails?", "Forwards method calls to another object."],
		["What does helper_method do in Rails?", "Exposes controller methods to views."],
		["What does rescue_from do in Rails?", "Handles exceptions globally in controllers."],
		["What does mount do in Rails routes?", "Mounts engines or Rack apps."],
		["What does resources do in routes.rb?", "Generates RESTful routes automatically."],
		["What does namespace do in routes.rb?", "Groups routes/controllers under namespace."],
		["What does concern do in routes.rb?", "Reuses route definitions."],
		["What does deliver_later do in Rails?", "Queues email delivery asynchronously."],
		["What does perform_later do in ActiveJob?", "Queues background job asynchronously."],
		["What does authenticate_user! do in Devise?", "Requires authenticated user access."],
		["What does current_user do in Devise?", "Returns authenticated user."],
		["What does pundit_user do?", "Defines authorization user context in Pundit."],
		["What does policy do in Pundit?", "Retrieves authorization policy object."],
		["What does policy_scope do in Pundit?", "Filters records based on authorization rules."]
	],
	"SQL" => [
		["What does SELECT do in SQL?", "Retrieves data from database tables."],
		["What does INSERT do in SQL?", "Adds new rows to a table."],
		["What does UPDATE do in SQL?", "Modifies existing table rows."],
		["What does DELETE do in SQL?", "Removes rows from a table."],
		["What does WHERE do in SQL?", "Filters query results by condition."],
		["What does ORDER BY do in SQL?", "Sorts query results."],
		["What does GROUP BY do in SQL?", "Groups rows for aggregation."],
		["What does HAVING do in SQL?", "Filters grouped results."],
		["What does LIMIT do in SQL?", "Restricts number of returned rows."],
		["What does OFFSET do in SQL?", "Skips rows before returning results."],
		["What does COUNT do in SQL?", "Counts rows."],
		["What does SUM do in SQL?", "Adds numeric values."],
		["What does AVG do in SQL?", "Calculates average value."],
		["What does MIN do in SQL?", "Returns minimum value."],
		["What does MAX do in SQL?", "Returns maximum value."],
		["What does DISTINCT do in SQL?", "Removes duplicate results."],
		["What is a PRIMARY KEY?", "Unique identifier for table rows."],
		["What is a FOREIGN KEY?", "Reference linking records between tables."],
		["What is a JOIN?", "Combines rows from multiple tables."],
		["What is an INNER JOIN?", "Returns matching rows from both tables."],
		["What is a LEFT JOIN?", "Returns all left-table rows plus matching right-table rows."],
		["What is a RIGHT JOIN?", "Returns all right-table rows plus matching left-table rows."],
		["What is a FULL OUTER JOIN?", "Returns all matching and non-matching rows from both tables."],
		["What is an index in SQL?", "Data structure improving query performance."],
		["What is normalization?", "Structuring DB tables to reduce redundancy."],
		["What is denormalization?", "Adding redundancy to improve read performance."],
		["What is a transaction?", "Group of DB operations executed atomically."],
		["What does COMMIT do?", "Permanently saves transaction changes."],
		["What does ROLLBACK do?", "Reverts transaction changes."],
		["What is ACID?", "Atomicity, Consistency, Isolation, Durability."],
		["What is a schema?", "Logical organization of DB objects/tables."],
		["What is a view in SQL?", "Virtual table based on query results."],
		["What is a subquery?", "Query nested inside another query."],
		["What is a CTE?", "Common Table Expression using WITH clause."],
		["What is a UNION?", "Combines results from multiple SELECT queries."],
		["What is UNION ALL?", "Combines results including duplicates."],
		["What is a many-to-many relationship?", "Records associated through join table."],
		["What is a one-to-many relationship?", "One record associated with many others."],
		["What is a unique constraint?", "Prevents duplicate values in column."],
		["What is NOT NULL?", "Requires column to contain value."],
		["What is a deadlock?", "Two transactions blocking each other indefinitely."],
		["What is query optimization?", "Improving SQL query performance."],
		["What causes slow SQL queries?", "Missing indexes, N+1 patterns, large scans, bad joins."],
		["What is EXPLAIN in SQL?", "Displays query execution plan."],
		["What is a sequential scan?", "Full table scan operation."],
		["What is a composite index?", "Index covering multiple columns."],
		["What is cardinality in SQL?", "Uniqueness/distribution of column values."],
		["What is replication?", "Copying DB data across servers."],
		["What is sharding?", "Splitting database horizontally across machines."],
		["What is eventual consistency?", "Data synchronizes over time instead of instantly."],
		["What is pessimistic locking?", "Preventing concurrent modifications via locks."],
		["What is optimistic locking?", "Detecting conflicting updates without locking."],
		["What is SQL injection?", "Security attack injecting malicious SQL statements."],
		["How do parameterized queries help security?", "Prevent SQL injection attacks."],
		["What is a migration in Rails/SQL context?", "Version-controlled database schema changes."],
		["What is referential integrity?", "Ensuring relationships between tables remain valid."]
	]
}

desired_slugs = flashcard_bank.keys.map { |name| name.parameterize }

Category.where.not(slug: desired_slugs).destroy_all

flashcard_bank.each do |category_name, cards|
	slug = category_name.parameterize
	category = Category.find_or_initialize_by(slug: slug)
	category.name = category_name
	category.save!

	desired_questions = cards.map(&:first)

	cards.each_with_index do |(question, answer), index|
		flashcard = category.flashcards.find_or_initialize_by(question: question)
		flashcard.answer = answer
		flashcard.position = index + 1
		flashcard.save!
	end

	category.flashcards.where.not(question: desired_questions).delete_all
end

puts "Seeded #{Category.count} categories and #{Flashcard.count} flashcards."
